# Generated by Django 5.1.4 on 2025-08-11 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CyberCellReport',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_date', models.CharField(max_length=255)),
                ('mail_date', models.CharField(max_length=255)),
                ('mail_month', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(max_length=255)),
                ('reference_number', models.CharField(max_length=255)),
                ('police_station_address', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=255)),
                ('email_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('picked', 'Picked'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('ageing_days', models.CharField(blank=True, max_length=255, null=True)),
                ('debit_from_bank', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('region', models.CharField(max_length=255)),
                ('utr_number', models.CharField(max_length=255)),
                ('utr_amount', models.CharField(max_length=255)),
                ('transaction_datetime', models.CharField(max_length=255)),
                ('total_fraudulent_amount', models.CharField(max_length=255)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='uploaded_pdfs/')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cyber_report',
                'managed': True,
            },
        ),
    ]
